"""Top-level compatibility module for Leoma exports."""
from leoma.delivery.commands import cli
from leoma.bootstrap import (
    emit_log as log,
    emit_header as log_header,
    CHUTES_API_URL,
    CHUTES_API_KEY,
    CLIP_DURATION,
    EPOCH_LEN,
    HOTKEY_NAME,
    HIPPIUS_ENDPOINT,
    HIPPIUS_REGION,
    HIPPIUS_SAMPLES_READ_ACCESS_KEY,
    HIPPIUS_SAMPLES_READ_SECRET_KEY,
    HIPPIUS_SAMPLES_WRITE_ACCESS_KEY,
    HIPPIUS_SAMPLES_WRITE_SECRET_KEY,
    HIPPIUS_VIDEOS_READ_ACCESS_KEY,
    HIPPIUS_VIDEOS_READ_SECRET_KEY,
    HIPPIUS_VIDEOS_WRITE_ACCESS_KEY,
    HIPPIUS_VIDEOS_WRITE_SECRET_KEY,
    MAX_VIDEO_HISTORY,
    MIN_VIDEO_SIZE,
    NETUID,
    NETWORK,
    MAX_VIDEO_SIZE,
    OBJECT_STORAGE_BACKEND,
    OPENAI_API_KEY,
    REQUEST_TIMEOUT,
    SAMPLES_BUCKET,
    SOURCE_BUCKET,
    USED_VIDEOS,
    WALLET_NAME,
)
from leoma.infra.storage_backend import (
    create_minio_client,
    create_samples_read_client,
    create_samples_write_client,
    create_source_read_client,
    create_source_write_client,
    ensure_bucket_exists,
    upload_sample,
)
from leoma.infra.judge import (
    forced_choice_comparison_async,
    get_description_async,
    evaluate_generated_video_async,
)
from leoma.infra.commit_parser import parse_commit as _parse_commit
from leoma.infra.video_utils import (
    choose_one_shot_clip_start,
    detect_scene_cuts,
    extract_clip,
    extract_first_frame,
    extract_frames,
    frames_to_base64,
    get_video_duration,
    stitch_videos_side_by_side,
)
from leoma.app.scorer.main import calculate_scores_from_samples
from leoma.app.validator.main import main, main_sync, run_epoch, step

__all__ = [
    "cli",
    "main",
    "main_sync",
    "NETUID",
    "EPOCH_LEN",
    "REQUEST_TIMEOUT",
    "CHUTES_API_URL",
    "CHUTES_API_KEY",
    "WALLET_NAME",
    "HOTKEY_NAME",
    "NETWORK",
    "OBJECT_STORAGE_BACKEND",
    "HIPPIUS_ENDPOINT",
    "HIPPIUS_REGION",
    "HIPPIUS_SAMPLES_READ_ACCESS_KEY",
    "HIPPIUS_SAMPLES_READ_SECRET_KEY",
    "HIPPIUS_VIDEOS_READ_ACCESS_KEY",
    "HIPPIUS_VIDEOS_READ_SECRET_KEY",
    "HIPPIUS_VIDEOS_WRITE_ACCESS_KEY",
    "HIPPIUS_VIDEOS_WRITE_SECRET_KEY",
    "HIPPIUS_SAMPLES_WRITE_ACCESS_KEY",
    "HIPPIUS_SAMPLES_READ_SECRET_KEY",
    "SOURCE_BUCKET",
    "SAMPLES_BUCKET",
    "OPENAI_API_KEY",
    "MIN_VIDEO_SIZE",
    "MAX_VIDEO_SIZE",
    "CLIP_DURATION",
    "USED_VIDEOS",
    "MAX_VIDEO_HISTORY",
    "log",
    "log_header",
    "create_source_read_client",
    "create_source_write_client",
    "create_samples_read_client",
    "create_samples_write_client",
    "create_minio_client",
    "ensure_bucket_exists",
    "upload_sample",
    "extract_frames",
    "frames_to_base64",
    "get_video_duration",
    "extract_clip",
    "extract_first_frame",
    "stitch_videos_side_by_side",
    "detect_scene_cuts",
    "choose_one_shot_clip_start",
    "get_description_async",
    "forced_choice_comparison_async",
    "evaluate_generated_video_async",
    "_parse_commit",
    "calculate_scores_from_samples",
    "run_epoch",
    "step",
]


if __name__ == "__main__":
    main_sync()
